config/routes.rb
Rails.application.routes.draw do
  # get 'welcome_pages/index'

  get 'customers/index', as: '/customers'

  devise_for :users

  scope '/admin' do
    resources :users
  end

  # root 'welcome_pages#index'
  root 'customers#index'

  resources :customers do
    collection do
      get 'check_all'
      post 'generate_pdf'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :postcode, presence: true, numericality: { only_integer: true }
  validates :province, presence: true
  validates :state, presence: true
  validates :phone_number, presence: true, numericality: { only_integer: true }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_info
  has_many :customers
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  respond_to :pdf

  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource_or_scope)
  	customers_url
  end

  def after_sign_out_path(resource_or_scope)
  	# URI.parse(request.referer).path if request.referer
    request.referrer || root_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :get_customer, only: %i[index new create]
  # before_action :authenticate_user!, only: %i[index new create edit update destroy]
  before_action :authenticate_user!

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)

    if @customer.save
      flash[:success] = 'Create a new customer is success'
      redirect_to @customer
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        docket = CustomerPdf.new(@customer, @store)
        send_data docket.render,
                  filename: "docket_#{@customer.created_at.strftime('%d/%m/%y/')}.pdf",
                  type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  def edit; end

  def update
    @customer = Customer.find(get_customer)
    if @customer.update_attribute(customer_params)
      flash[:success] = 'Edit a current customer is success'
      redirect_to @customer
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url
  end

  def check_all
    @customers = Customer.find(params[:customer_ids])

    respond_to do |format|
      format.html
      format.pdf do
        dockets = CustomersPdf.new(@customers)
        send_data dockets.render,
                  filename: 'dockets.pdf', type: 'application/pdf'
      end
    end
  end

  private

  def get_customer
    @customer = Customer.find_by(id: params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :address, :postcode, :province, :state, :phone_number)
  end
end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def redirect_to_main_page
		if current_user
			customers_url
		else
			root_path
		end
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map {|msg| content_tag(:li, msg)}.join

		html = <<-HTML
			<div class="alert alert-danger">
				<button class="close" type="button" data-dismiss="alert">x</button>
				#{messages}
			</div>
		HTML

		html.html_safe
	end
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/customers/_alert.html.erb
<div class="container">
  <div class="col-md-7 col-md-offset-2">
    <% if @customer.errors.any? %>
      <div class="alert alert-danger" id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this data from being saved:</h2>
        <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
  <div class="form-group">
    <%= f.label :name, 'name'.upcase %>
    <%= f.text_field :name, placeholder: 'Customer Name', class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :address, 'address'.upcase %>
    <%= f.text_area :address, placeholder: 'Customer Address', class: 'form-control', cols: 2, rows: 5 %>
  </div>
  <div class="form-group">
    <%= f.label :postcode, 'postcode'.upcase %>
    <%= f.text_field :postcode, placeholder: 'Customer Postcode', class: 'form-control', maxlength: 5 %>
  </div>
  <div class="form-group">
    <%= f.label :province, 'province'.upcase  %>
    <%= f.text_field :province, placeholder: 'Customer province', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state, 'state'.upcase %>
    <%= f.text_field :state, placeholder: 'Customer State', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, 'phone number'.upcase %>
    <%= f.text_field :phone_number, placeholder: 'Customer Phone Number', class: 'form-control', maxlength: 10 %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', redirect_to_main_page, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<%= render 'customers/alert', object: @customer %>
		<div>
			<h1>Edit Current Customer Form</h1>
		</div>
		<%= render 'customers/form' %>
	</div>
</div>

app/views/customers/index.html.erb
<div class="container">
  <div class="">
    <div>
      <h1>
        Customers List
      </h1>
      <div>
        <%= link_to 'Create Customer', new_customer_path, class: 'btn btn-primary' %>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="table-responsive">
      <%= form_tag check_all_customers_path do %>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th></th>
              <th class="text-center">Name</th>
              <th class="text-center">Address</th>
              <th class="text-center">Postcode</th>
              <th class="text-center">Province</th>
              <th class="text-center">State</th>
              <th class="text-center">Phone</th>
              <th class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td>
                  <%= check_box_tag 'customer_ids[]', customer.id %>
                </td>
                <td><%= link_to customer.name, edit_customer_path(customer) %></td>
                <td><%= customer.address %></td>
                <td class="text-center"><%= customer.postcode %></td>
                <td><%= customer.province %></td>
                <td><%= customer.state %></td>
                <td class="text-center"><%= customer.phone_number %></td>
                <td class="text-center">
                  <%= link_to 'Generate as PDF', customer_path(customer, format: 'pdf'), class: 'btn btn-xs btn-info' %>
                  <%= link_to 'Remove Customer', customer_path(customer), method: :delete, data: {confirm: 'You are about to delete this customer from your database. Are you sure want to continue?'}, class: 'btn btn-xs btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <span class="has-tooltip" data-toggle="tooltip" title="Coming Soon...">
          <%= link_to 'Generate all as PDF', generate_pdf_customers_path, class: 'btn disabled' %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="">
	<div class="col-md-8 col-md-offset-2">
		<%= render 'customers/alert', object: @customer %>
		<div>
			<h2>New Customer Form</h2>
		</div>
		<%= render 'customers/form' %>
	</div>
</div>

app/views/customers/show.html.erb
<div class="col-md-12">
  <div>
    <h1>Your Customer Information</h1>
  </div>
  <div class="panel">
    <div class="panel-body">
      <p>
        <h3>
          <strong>
            <%= @customer.name %>
          </strong>
        </h3>
        <p>
          <strong>Customer Address</strong>
          <%= @customer.address %>
        </p>
        <p>
          <strong>Customer Postcode</strong>
          <%= @customer.postcode %>
        </p>
        <p>
          <strong>Customer Province</strong>
          <%= @customer.province %>
        </p>
        <p>
          <strong>Customer State</strong>
          <%= @customer.state %>
        </p>
        <p>
          <strong>Customer Phone Number</strong>
          <%= @customer.phone_number %>
        </p>
      </p>
    </div>
  </div>
  <div>
    <%= link_to 'Edit Customer', edit_customer_path(@customer), class: 'btn btn-info' %>
    <%= link_to 'Previous Page', customers_url, class: 'btn btn-danger' %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Store Management', redirect_to_main_page, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Customers', customers_path %>
        </li>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="disabled"><a href="#">View Profile</a></li>
              <li><%= link_to 'Manage Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Log in', new_user_session_path %>
          </li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        </ul>
      <% end %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Store Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
    <%= render 'partials/notice' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_notice.html.erb
<div class="container">
	<div class="col-md-10 col-md-offset-1">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<a href="#" class="close" data-dismiss="alert">x</a>
				<%= value %>
			</div>
		<% end %>		
	</div>
</div>

app/views/welcome_pages/index.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="jumbotron">
      <h2 style="text-align: center;">Welcome to My Store Management System</h2>
      <h4 style="text-align: center;">
        Please sign in to manage your parcels and customers.
      </h4>
      <% if current_user  %>
        <%= link_to 'Continue', customers_path %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path %>
      <% end %>
    </div>
  </div>
</div>